### ISSUE TITLE
Publish .ipa release?

### ISSUE THREAD

**Issue by Johnny5sword** [tejas-xd/Pancake#1]
Hello!

It would be great if the .ipa is available so iOS users can sideload this app using [Altstore](https://altstore.io/)(iOS 12.2+) or [Sideloadly](https://sideloadly.io/)(iOS 7+).

Unfortunately, I can't build it because I don't have a mac or know others who have one.

If it is released, I also hope it can be installed on arm7v 32-bit iOS 9.3 because it's the last OS version available for my device.
Thank you!

Edit: It looks like [Flutter SDK](https://docs.flutter.dev/development/tools/sdk/releases?tab=macos) versions [2.10.5](https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip)(Stable), April 2022 and [2.13.0-0.4.pre](https://storage.googleapis.com/flutter_infra_release/releases/beta/macos/flutter_macos_2.13.0-0.4.pre-beta.zip)(Beta), May 2022 were the last releases to support arm7v 32-bit iOS such as my version of iOS 9 based from this [document](https://docs.google.com/document/d/1Xz8B2w42ZGmrSdvQHo6LVLhiSZBIxnHxZxoZ-8oyRUc/mobilebasic).

**Comment by brnwlshubh** [comment]
.apk release too @tejas-xd

**Comment by tejas-xd** [comment]
i dont have a mac either
