### ISSUE TITLE
Mandatory Google Sign In?

### ISSUE THREAD

**Issue by DarkCrypt** [tejas-xd/Pancake#15]
Pancake takes part as one of my go to movie streaming apps and I was excited to see the updated build(v.2.0) until I noticed there is now a mandatory Google sign in. No offense, but I am one of many who prefer to stay as far away from Google as possible. Because of this I can't get passed the sign in screen which makes this app unusable.

What's the reason for the mandatory sign in, syncing capabilities across devices? Is there any chance you would implement a way to bypass or skip this sign in process?

**Comment by tejas-xd** [comment]
added a apk release without google auth

**Comment by DarkCrypt** [comment]
Wow! Very fast and responsive! I apologize for the added work but it really is much appreciated. I can now keep this app in my arsenal, it looks great! You're truly a wonderful dev, much love and respect. You definitely deserve more than 2 👍👍! Thank you!
