### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by MrConqueror** [tejas-xd/Pancake#7]
Any future features?

**Comment by tejas-xd** [comment]
I will try to add firebase to save favorite movies and shows , improve ui and add more options to stream from

**Comment by MrConqueror** [comment]
> I will try to add firebase to save favorite movies and shows , improve ui and add more options to stream from

Cool, looking forward to seeing it

**Comment by VikramadityaDev** [comment]
how do I stream movies
